blog/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.index),#要把url分配到相应的方法中去
    url(r'^article/(?P<article_id>\d+)$', views.article_page,name='article_page'),
    url(r'^edit/(?P<article_id>\d+)$',views.edit_page,name='edit_page'),
    url(r'^edit/action/$',views.edit_action,name='edit_action'),
]

myweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# import blog.views as bv

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog')),#要把url分配到相应的方法中去
]

blog/models.py
from django.db import models

# Create your models here.(Use ORM to operate SQL)
class Article(models.Model):
    title = models.CharField(max_length=32, default='title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(auto_now=True,null=True)
    def __str__(self):
        return self.title # 在admin中数据库显示内容标题，若不重写__str__函数，就会显示‘Article’

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.
def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles':articles})

def article_page(request,article_id):
    article = models.Article.objects.get(pk = article_id)
    return render(request, 'blog/article_page.html', {'article':article})

def edit_page(request, article_id):
    if str(article_id)=='0':
        return render(request, 'blog/edit_page.html')
    else:
        article = models.Article.objects.get(pk=article_id)
        return render(request, 'blog/edit_page.html',{'article':article})

def edit_action(request):
    title = request.POST.get('title',"TITLE")
    content = request.POST.get('content','CONTENT')#
    article_id = request.POST.get('article_id','0')
    if article_id:
        article = models.Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
    else:
        models.Article.objects.create(title=title,content=content)
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})

templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/><br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}

{#    {% if article.id %}#}
{#        <input type="hidden" name="article_id" value="{{ article.id }}">#}
{#        <lable>文章标题#}
{#            <input type="text" name="title" value="{{ article.title }}"/>#}
{#        </lable>#}
{#        <br/>#}
{#        <lable>文章内容#}
{#            <input type="text" name="content" value="{{ article.content }}"/>#}
{#        </lable>#}
{#        <br/>#}
{#        <input type="submit" name="提交" id="SubmitButton">#}
{#    {% else %}#}
{#        <input type="hidden" name="article_id" value="0">#}
{#        <lable>文章标题#}
{#            <input type="text" name="title"/>#}
{#        </lable>#}
{#        <br/>#}
{#        <lable>文章内容#}
{#            <input type="text" name="content"/>#}
{#        </lable>#}
{#        <br/>#}
{#        <input type="submit" name="提交" id="SubmitButton">#}
{#    {% endif %}#}


    <input type="hidden" name="article_id" value="{{ article.id | default:'0'}}">
    <lable>文章标题
        <input type="text" name="title" value="{{ article.title }}"/>
    </lable>
    <br/>
    <lable>文章内容
        <input type="text" name="content" value="{{ article.content }}"/>
    </lable>
    <br/>
    <input type="submit" name="提交" id="SubmitButton">

</form>
</body>
</html>

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">编写新文章</a>

</h1>
{% for article in articles%}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br/>
{% endfor %}
</body>
</html>